/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Clases.Pasajero;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dairo Arenas
 */
public class Form_Principal extends javax.swing.JFrame {
    HashMap<String, String> hashmap = new HashMap<>();
    /**
     * Creates new form Form_Principal
     */
    JCheckBox[] checkBoxesA;
    JCheckBox[] checkBoxesB; 
    DefaultTableModel model_;
    public Form_Principal() {
        initComponents();
        this.checkBoxesA = new JCheckBox[]{A1, A2, A3, A4, A5};
        this.checkBoxesB = new JCheckBox[]{B1, B2, B3, B4, B5};
        this.setLocationRelativeTo(null);
        
        

        LlenarAsiento(hashmap);
        
        
/*for(int j = 0; j < 5; j++){
            System.out.print(hashmap.get("A"+j));
            System.out.print(hashmap.get("B"+j));
        }*/
        
    }
    public final void DesmarcarCheckBoxes(JCheckBox[] checkBoxesA,JCheckBox[] checkBoxesB) {
        // Desmarcar todos los checkboxes en checkBoxesA
        for (JCheckBox checkBox : checkBoxesA) {
            if (checkBox != null) {
                checkBox.setSelected(false);
            }
        }

        // Desmarcar todos los checkboxes en checkBoxesB
        for (JCheckBox checkBox : checkBoxesB) {
            if (checkBox != null) {
                checkBox.setSelected(false);
            }
        }
    }
    public final void ValidarAsiento(HashMap hashmap, JCheckBox[] checkBoxesA, JCheckBox[] checkBoxesB){
        for (int i = 0; i < 5; i++) {
            if (hashmap.get("A" + i).equals("0")) { 
                checkBoxesA[i].setSelected(false); // Deselecciona si es "0"
            } else {
                checkBoxesA[i].setSelected(true); // Selecciona si es "1"
            }

            // Verificar y asignar el estado de los checkboxes de B
            if (hashmap.get("B" + i).equals("0")) { 
                checkBoxesB[i].setSelected(false); // Deselecciona si es "0"
            } else {
                checkBoxesB[i].setSelected(true); // Selecciona si es "1"
            }
        }

    }
    
    public static void LlenarAsiento(HashMap hashmap){
        // Ciclo para recorrer las checkboxes
        for (int i = 0; i < 5; i++) {
            // Asigna "0" a las entradas A0, A1, ..., A4 (disponible)
            hashmap.put("A" + i, "0"); // Asignar "0" para indicar que está disponible
            hashmap.put("B" + i, "0"); // Asignar "0" para indicar que está disponible
        }
    }
    
    public static void LlenarAsiento(HashMap hashmap,Pasajero pasajero){
        hashmap.put(pasajero.getAsiento(),"1");
    }
    
    public void AsignarPasajero(HashMap hashmap,Pasajero pasajero) {
        // Crear el DefaultTableModel
        model_ = TableModel(); // Asegúrate de que TableModel() retorne el modelo correctamente

        // Llenar el modelo con los datos del pasajero
        LLenarModel(model_, pasajero); 

        // Establecer el modelo en la tabla
        TablePasajero.setModel(model_);

        // Actualizar los asientos en el HashMap según el pasajero
        LlenarAsiento(hashmap, pasajero);

        // Validar y actualizar el estado de los JCheckBox según el HashMap
        ValidarAsiento(hashmap,checkBoxesA,checkBoxesB);
        
    }
    
    public DefaultTableModel TableModel(){
        DefaultTableModel model = (DefaultTableModel) TablePasajero.getModel();

            // Si no has añadido las columnas antes, puedes hacerlo aquí (solo una vez)
            if (model.getColumnCount() == 0) {
                model.addColumn("Documento");
                model.addColumn("Nombre");
                model.addColumn("Asiento");
            }
        return model;    
    }
    
    public void LLenarModel(DefaultTableModel model,Pasajero pasajero){
        model.addRow(new Object[]{
            pasajero.getDocumento(), 
            pasajero.getNombre(), 
            pasajero.getAsiento()
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        A1 = new javax.swing.JCheckBox();
        B1 = new javax.swing.JCheckBox();
        A2 = new javax.swing.JCheckBox();
        B2 = new javax.swing.JCheckBox();
        A3 = new javax.swing.JCheckBox();
        B3 = new javax.swing.JCheckBox();
        A4 = new javax.swing.JCheckBox();
        B4 = new javax.swing.JCheckBox();
        A5 = new javax.swing.JCheckBox();
        B5 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnAsignar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablePasajero = new javax.swing.JTable();
        BtnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("A");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 85, 18, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("B");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 115, 18, -1));

        A1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A1.setEnabled(false);
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        jPanel1.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        B1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        B1.setEnabled(false);
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        A2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A2.setEnabled(false);
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        jPanel1.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 90, -1, -1));

        B2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        B2.setEnabled(false);
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 120, -1, -1));

        A3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A3.setEnabled(false);
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        jPanel1.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        B3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        B3.setEnabled(false);
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel1.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        A4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A4.setEnabled(false);
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        jPanel1.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        B4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        B4.setEnabled(false);
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel1.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        A5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A5.setEnabled(false);
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        jPanel1.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        B5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        B5.setEnabled(false);
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jPanel1.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("0");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 150, 18, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 18, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 150, 18, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 150, 18, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 150, 18, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avion.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 230));

        BtnAsignar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnAsignar.setText("Asignar Asiento");
        BtnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarActionPerformed(evt);
            }
        });

        TablePasajero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre", "Asiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablePasajero);

        BtnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void BtnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarActionPerformed
    
        // Verificar que el hashmap no esté vacío
        if (hashmap == null || hashmap.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay asientos disponibles para asignar.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir si no hay datos
        }

        // Crear y mostrar el formulario de pasajero
        Form_Pasajero pasajero = new Form_Pasajero(hashmap, Form_Principal.this);
        pasajero.setVisible(true);
        pasajero.setLocationRelativeTo(null);
        pasajero.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_BtnAsignarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int filaseleccionada = TablePasajero.getSelectedRow();
        String asientoPasajero;
        //tableEstudiante.remove
        model_ = TableModel();
        
        asientoPasajero = model_.getValueAt(filaseleccionada, 2).toString();
        
        hashmap.put(asientoPasajero,"0");
        
        ValidarAsiento(hashmap,checkBoxesA,checkBoxesB);
        //System.out.println(asientoPasajero);
        if(filaseleccionada != -1){
            model_.removeRow(filaseleccionada);
        }
        JOptionPane.showMessageDialog(null, "Registro eliminado");
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A1;
    private javax.swing.JCheckBox A2;
    private javax.swing.JCheckBox A3;
    private javax.swing.JCheckBox A4;
    private javax.swing.JCheckBox A5;
    private javax.swing.JCheckBox B1;
    private javax.swing.JCheckBox B2;
    private javax.swing.JCheckBox B3;
    private javax.swing.JCheckBox B4;
    private javax.swing.JCheckBox B5;
    private javax.swing.JButton BtnAsignar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JTable TablePasajero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
